[default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = ['@forge-std/=lib/forge-std/', '@contracts/=contracts/']
ffi = true
auto_detect_solc = true
verbosity = 5

[build]
src = 'src'
out = 'bout'                   # output directory conflicts with dapptools
libs = ['lib']
auto_detect_solc = true
remappings = [
    '@utils/=src/utils/',
    '@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    '@contracts/=src/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'ds-test/=lib/ds-test/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
]
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
